### PR TITLE
rewrite kafka connector

### PR DESCRIPTION
**Pull request by ekneg54**
this PR rewrites the confluent kafka input and output processors with focus on the input side.
please take a look at the CHANGELOG.md for changes.

### CODE REVIEW

**Comment by ekneg54** [comment]
rebased from main.

@ppcad now it`s ready to rumble 👍

**Comment by ekneg54** [comment]
it is possible, that the `statistics.interval.ms` default was too low. It was set to 1s. I increased the default to 30 seconds.

**Comment by ppcad** [comment]
> I added a validation for mandatory keys in kafka_config object. This prevents the Exceptions during start and logs the missing keys.

Thanks for the changes. This solves the problem.

**Comment by ppcad** [comment]
> it is possible, that the `statistics.interval.ms` default was too low. It was set to 1s. I increased the default to 30 seconds.

This does not seem to be the reason for the performance loss.

It seems that the new version is faster than the old one with 1 process, but slower once I increase the amount up to the partition count.

**Review by ppcad — APPROVED** [review]

**Pull request merged**
