### PR TITLE
add timestamper processor

### PR DESCRIPTION
**Pull request by ekneg54**
this extracts the `timestamp` functionality from normalizer to a separate processor.
During this work, I encapsulated all time related parsing functionality (excluding in datetime_extractor) in `logprep.util.time` to prevent spreading usage of external libs all over the codebase. This should make it easier to replace dependencies in the future.

- [x] add rules and processor boilerplate
- [x] implement processor and rules 
- [x] add tests
- [x] add documentation
- [x] add jupyther processor case example
- [x] improve timestampdiffer performance by using ciso8601 parser
- [x] revise other timestamp parsing locations in logprep and check improvement by using ciso8601

this PR enforces that iso8601 is the default timestamp format and introduces `ciso8601` as a fast lib to parse iso8601 compliant time strings.

here are the benchmarks against arrow:

```python
>>> from timeit import timeit
>>> setup_code = """
... import arrow
... import ciso8601
... """
>>> timeit("ciso8601.parse_datetime('2000-12-31T22:59:59+00:00')", setup_code)
0.0749997069942765
>>> timeit("arrow.get('2000-12-31T22:59:59+00:00')", setup_code)
38.91713571699802
```

here are the benchmark against dateutil (used in normalizer):
```python
>>> from timeit import timeit
>>> setup_code = """
... from dateutil import parser
... import ciso8601
... """
>>> timeit("ciso8601.parse_datetime('2000-12-31T22:59:59+00:00')", setup_code)
0.05876832699868828
>>> timeit("ciso8601.parse_datetime('2000-12-31T22:59:59+00:00')", setup_code)
0.0625361469865311
>>> timeit("ciso8601.parse_datetime('2000-12-31T22:59:59+00:00')", setup_code)
0.06355366201023571
>>> timeit("parser.isoparse('2000-12-31T22:59:59+00:00')", setup_code)
3.577728838979965
>>> 
```

get the current time and formatted output (datetime vs arrow):

```python
>>> setup_code = """
... from datetime import datetime
... import arrow
... """
>>> from timeit import timeit
>>> timeit("datetime.now().strftime('%y:%m:%d')", setup_code)
1.300148893991718
>>> timeit("arrow.now().format('YY:MM:DD')", setup_code)
11.406668618001277
```
performance improvement vs main branch:

```python
pwsh> git checkout main                                                                                                                                                                                  Switched to branch 'main'                                                                                                                                                                                
Your branch is up to date with 'origin/main'.
pwsh> & /home/vagrant/external_work/Logprep/.venv/bin/python /home/vagrant/external_work/Logprep/performance.py                                                                                          2.6355724270106293                                                                                                                                                                                       
2.247861991985701
2.281490693014348
pwsh> git checkout dev-add-timestamper-processor                                                                                                                                                         Switched to branch 'dev-add-timestamper-processor'                                                                                                                                                       
Your branch is up to date with 'origin/dev-add-timestamper-processor'.
pwsh> & /home/vagrant/external_work/Logprep/.venv/bin/python /home/vagrant/external_work/Logprep/performance.py                                                                                          2.0163544649840333                                                                                                                                                                                       
1.5601382740132976
1.3560994770086836
pwsh> & /home/vagrant/external_work/Logprep/.venv/bin/python /home/vagrant/external_work/Logprep/performance.py                                                                                          1.3588259509997442                                                                                                                                                                                       
1.3510418919904623
1.3812679010152351
```

testcode as usual:

```python
from timeit import timeit

setup_code = """
import logging
logging.disable(logging.CRITICAL)
import json
from pathlib import Path
from logprep.framework.pipeline import Pipeline
from logprep.util.configuration import Configuration

input_data = Path("kafka_messages").read_text().splitlines()[:20000]
input_data = [json.loads(item) for item in input_data]
config = Configuration.create_from_yaml("config/pipeline.yml")
del config["output"]
config.update({"input": {"dummy": {"type": "dummy_input", "documents": input_data}}})
pipeline = Pipeline(config=config)
pipeline.process_pipeline()
"""

profile_code = """
for i in input_data:
    extra_outputs = pipeline.process_pipeline()
"""

print(timeit(stmt=profile_code, setup=setup_code, number=1))
print(timeit(stmt=profile_code, setup=setup_code, number=1))
print(timeit(stmt=profile_code, setup=setup_code, number=1))

```

### CODE REVIEW

**Comment by ekneg54** [comment]
I have no clue, why the docs not building. I do not think it depends on my changes.

**Comment by ekneg54** [comment]
@ppcad could you please validate the performance improvement and check for breaking issues with this PR?

**Comment by ekneg54** [comment]
rebased from main

**Review by sashs — APPROVED** [review]

**Comment by ekneg54** [comment]
Had to merge it, because I won't be here the next 4 weeks... And this should not block.

**Pull request merged**
