### PR TITLE
add kafka advanced config option

### PR DESCRIPTION
**Pull request by ekneg54**

### CODE REVIEW

**Comment by ekneg54** [comment]
closes #163 
closes #356

**Review by ppcad — CHANGES_REQUESTED** [review]
Thanks, this works, but there is a problem when adding a value that requires a dict and not a string, like `offset_reset_policy`.

Furthermore, setting the advanced kafka configuration does completely overwrite the existing configuration, so that all configuration must be done there and the validator does still require the existence of the other configuration parameters, which means that the configuration is being doubled.

Could this be changed, so that the validator does not require both configs or that only existing parameters of the `kafka_config` are being used to replace the old config?

**Comment by ekneg54** [comment]
and we had some struggles with the Changelog, wich were not updated possibly in cause of merge conflicts

**Review by ppcad — APPROVED** [review]
Thank you for the chages!

**Pull request merged**
