### PR TITLE
S3 output

### PR DESCRIPTION
**Pull request by ppcad**
Add non-blocking s3 output connector that doesn't disrupt processing in case of connection issues.

### CODE REVIEW

**Review by ekneg54 — CHANGES_REQUESTED** [review]
Please add your connector to the documentation

**Comment by ppcad** [comment]
I have added the documentation. The fails of the checks do not seem to be caused by this branch.

**Comment by ekneg54** [comment]
we will check the failing tests

**Review by ekneg54 — APPROVED** [review]
Thank you @dtrai2  for fixing the pipeline.
Thank you @ppcad for this PR.

**Pull request merged**
