### PR TITLE
refactor list comparison tests to use base class

### PR DESCRIPTION
**Pull request by urdit52**
Refactor to use base class for list comparison tests. Part of a refactoring for all processors to use generic and specific rules.

### CODE REVIEW

**Review by dtrai2 — COMMENTED** [review]
lgtm

**Comment by ekneg54** [comment]
look to this commit to solve the problems with ProcessorStats object: 3b152a1824bf8b9df2bf8ab0a29347ef0d7966c5

**Comment by urdit52** [comment]
@dtrai2 : minor changes, could you please re-check?

**Review by dtrai2 — COMMENTED** [review]
done, looks still good to me

**Comment by ekneg54** [comment]
> done, looks still good to me

@dtrai2 then please approve so @ppcad is able to merge 👍

**Review by ppcad — APPROVED** [review]

**Review by dtrai2 — APPROVED** [review]

**Comment by ppcad** [comment]
Could you please resolve the conflict?

**Comment by ppcad** [comment]
Could you please resolve the conflict?

**Comment by urdit52** [comment]
sure, will rebase.

**Comment by urdit52** [comment]
rebased, tested, ready for merge.

**Pull request merged**
