### PR TITLE
time measurement checks for caller class name now

### LINKED ISSUE #434: Deleter doesn't delete logs
When using the deleter, nothing is deleted and an empty file is dragged through the whole pipeline resulting in only containing the processing times in the meta-data.

**Expected behavior**

Immediately deletes the log when filter of deleter matches in preprocessor step.

**Current behavior**

Creates an empty dictionary thats entirely processed and at the end, cause of a non existing index gets written into default instead.

**Steps to reproduce**

1. Running Logprep
2. Enabling the preprocessor **deleter**
3. Look at default index

**Environment**

Logprep version: 23.07.03
Python version: 3.11
Enviroment: Kubernetes with containerd

### PR DESCRIPTION
**Pull request by dtrai2**
the test also checks now for an actual deleter implementation

closes #434

### CODE REVIEW

**Comment by ppcad** [comment]
Thank you for changing this, but the other problem was, that the pipeline adds time measurements, even after it has been removed by the deleter processor. It is called after all events have been processed.

Maybe check for `name = "pipeline"` in `time_measurement.py` and only add the times if the event is not empty.

**Comment by ekneg54** [comment]
How about to remove the feature to write metrics to events completely in favor of the Prometheus exporter?

**Comment by ppcad** [comment]
I still need it at the moment.

**Comment by dtrai2** [comment]
okay, well then I remove checking who tries to write the times into the event and just assume that if the event is empty no measurement time is needed.

**Review by ppcad — APPROVED** [review]
Thank you, it works!

**Pull request merged**
