### PR TITLE
Logprep 4.0.0 release

### PR DESCRIPTION
**Pull request by ekneg54**

### CODE REVIEW

**Comment by ppcad** [comment]
Maybe highlight in the rule language section that `source_fields` is now a list, to prevent confusion.
Furthermore, the documentation for the new naming scheme is missing for the `datetime_extractor`.

**Review by ppcad — CHANGES_REQUESTED** [review]
Maybe highlight in the rule language section that `source_fields` is now a list, to prevent confusion.
Furthermore, the documentation for the new naming scheme is missing for the `datetime_extractor`.

**Comment by ekneg54** [comment]
thank you @ppcad.
I revised the documentation.

**Review by ppcad — APPROVED** [review]
Thank you for the changes. Looks good to me.

**Review by urdit52 — APPROVED** [review]
After ppcads requested changes: thank you, looks good to me.

**Pull request merged**
