### PR TITLE
improve connector performance

### PR DESCRIPTION
**Pull request by ekneg54**
use `msgspec.json` instead of builtin `json` module. This should lead to a significant performance boost in input and output connectors.

### CODE REVIEW

**Review by ppcad — CHANGES_REQUESTED** [review]
The tests pass, but a FatalOutputError is raised in Opensearch if Logprep is run. It is unable to serialize the events. I assume this also happens for Elasticsearch.

**Comment by ekneg54** [comment]
thank you... I will investigate it

**Comment by ekneg54** [comment]
I reverted the change for the open- and elasticsearch error document building.

**Review by ppcad — APPROVED** [review]
Thanks for the changes, it works now!

**Pull request merged**
